name: build
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4.5
            gemfile: Gemfile
          - ruby: 2.7.5
            gemfile: gemfiles/Gemfile-6-1
          - ruby: 3.4.5
            gemfile: gemfiles/Gemfile-7-0
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RAILS_ENV: test
      ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
      ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      ALIYUN_OSS_BUCKET: ${{ secrets.ALIYUN_OSS_BUCKET }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: "Test"
        run: bundle exec rake test
